apiVersion: apps/v1
kind: Deployment
metadata:
  name: letsencrypt-vault-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: letsencrypt-vault-manager
  template:
    metadata:
      labels:
        app: letsencrypt-vault-manager
    spec:
      serviceAccountName: letsencrypt-vault-manager
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - letsencrypt-vault-manager
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
        - name: letsencrypt-vault-manager
          image: gobadiah/letsencrypt-vault-manager:0.19
          ports:
            - containerPort: 80
              name: http
          env:
            - name: VAULT_ROLE
              value: letsencrypt-vault-manager
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: CLUSTER_NAME
