apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nginx
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
        - name: nginx
          image: nginx:1.13
          ports:
            - containerPort: 443
              name: ssl
          volumeMounts:
            - name: tls
              mountPath: /etc/vault-tls
            - name: config
              mountPath: /etc/nginx/conf.d
        - name: dnsmasq
          image: "janeczku/go-dnsmasq:release-1.0.5"
          args:
            - --listen
            - "127.0.0.1:53"
            - --default-resolver
            - --append-search-domains
            - --hostsfile=/etc/hosts
            - --verbose
      volumes:
        - name: tls
          secret:
            secretName: vault-certificates
        - name: config
          configMap:
            name: nginx-config
