apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: vault-nginx
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nginx
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
        - name: nginx
          image: gobadiah/vault-k8s-consul-template-nginx:0.6
          ports:
            - containerPort: 443
              name: ssl
          env:
            - name: VAULT_ROLE
              value: vault-nginx
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: CLUSTER_NAME
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
            - name: consul-template
              mountPath: /consul-template
        - name: dnsmasq
          image: "janeczku/go-dnsmasq:release-1.0.5"
          args:
            - --listen
            - "127.0.0.1:53"
            - --default-resolver
            - --append-search-domains
            - --hostsfile=/etc/hosts
            - --verbose
      volumes:
        - name: config
          configMap:
            name: nginx-config
        - name: consul-template
          configMap:
            name: consul-template-config
