apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-template-config
  namespace: default
data:
  config.hcl: |
    vault {
      ssl {
        verify = false
      }
    }
    exec {
      command = "nginx -g \"daemon off;\""
    }

    template {
      destination = "/etc/vault-tls/fullchain.pem"

      contents = "{{ with secret \"secret/certs/consul-2.codefiction.io\" }}{{ index .Data \"fullchain.pem\" }}{{ end }}"
    }

    template {
      destination = "/etc/vault-tls/privkey.pem"

      contents = "{{ with secret \"secret/certs/consul-2.codefiction.io\" }}{{ index .Data \"privkey.pem\" }}{{ end }}"
    }
