apiVersion: v1
kind: Service
metadata:
  name: letsencrypt-vault-manager
  labels:
    name: letsencrypt-vault-manager
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
  selector:
    app: letsencrypt-vault-manager
